import { Container, Divider } from "@chakra-ui/react";
import axios from "axios";
import {
  GetServerSideProps,
  InferGetServerSidePropsType,
  NextPage,
} from "next";
import Head from "next/head";
import { Layout } from "../components";
import { API_URL } from "../constants";
import { IItemListing } from "../model/items.mode";

export const getServerSideProps: GetServerSideProps<{
  items: IItemListing[];
}> = async () => {
  let items: IItemListing[] = [];

  try {
    const res = await axios.get<IItemListing[]>(`${API_URL}/item-listing`);

    if (res.data && res.data.length > 0) {
      items = res.data;
    }
  } catch (error) {
    console.error(error);
  }
  return {
    props: {
      items,
    },
  };
};

const HomePage: NextPage<
  InferGetServerSidePropsType<typeof getServerSideProps>
> = ({ items }) => {
  return (
    <>
      <Head>
        <title>Craigslist Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Container mt="16" maxW="container.sm">
          {items.map((item) => {
            return <div key={item.id}>{item.title}</div>;
          })}
        </Container>
      </Layout>
    </>
  );
};

export default HomePage;
