import { Container } from "@chakra-ui/react";
import { NextPage } from "next";
import Head from "next/head";
import React from "react";
import { Layout } from "../components";
import RegisterLoginForm from "../components/RegisterLoginForm";

const Login: NextPage = ({}) => {
  return (
    <>
      <Head>
        <title>Craigslist Clone | Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Container mt="8" maxW="container.sm">
          <RegisterLoginForm action="login" />
        </Container>
      </Layout>
    </>
  );
};

export default Login;
