import { Box, Button, Container, Heading, Text } from "@chakra-ui/react";
import { NextPage } from "next";
import Head from "next/head";
import React, { useContext } from "react";
import { Layout, NextChakraLink } from "../components";
import { AppUserContext } from "./_app";

const SellItemPage: NextPage = ({}) => {
  const [user] = useContext(AppUserContext);

  return (
    <>
      <Head>
        <title>Craigslist Clone | Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Container mt="8" maxW="600px" textAlign="center">
          {!user.username || !user.token ? (
            <Box>
              <Heading as="h3" fontSize="2xl" fontWeight="medium" mb="6">
                Not Logged In
              </Heading>
              <NextChakraLink href={`/login`}>
                <Button>Login</Button>
              </NextChakraLink>
            </Box>
          ) : (
            <Box></Box>
          )}
        </Container>
      </Layout>
    </>
  );
};

export default SellItemPage;
