import { Container } from "@chakra-ui/react";
import { NextPage } from "next";
import Head from "next/head";
import React from "react";
import { Layout } from "../components";

const SellItemPage: NextPage = ({}) => {
  return (
    <>
      <Head>
        <title>Craigslist Clone | Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Container mt="8" maxW="600px">
          <form>
            {/* Although the API supports multi-image uploading in a single request, I'm going to only allow one image per upload */}
            <input type="file" />
          </form>
        </Container>
      </Layout>
    </>
  );
};

export default SellItemPage;
